apiVersion: v1
kind: Service
metadata:
  name: mfe-container-srv
  namespace: dev-01
  labels:
    name: mfe-container
spec:
  type: NodePort
  ports:
    - name: mfe-container
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30090
  selector:
    app: mfe-container
# kubectl get ns
# kubectl create namespace dev-01
# kubectl apply -f kube-deployment.yaml
# kubectl apply -f kube-service.yaml
# website:  http://localhost:30090

# clean up: kubectl delete namespace dev-01
